### ISSUE TITLE
Support for self-update?

### ISSUE THREAD

**Issue by dantleech** [my127/workspace#60] opened 2020-09-01 08:35 UTC
It would be great to have a `self-update` feature like, for example, `composer`.

I implemented this on [phpbench](https://github.com/phpbench/phpbench) with https://github.com/humbug/phar-updater although that package has since been abandoned for no given reason.

**Comment by jameshalsall** [comment] 2021-02-05 10:42
👍 this is a good idea, it's a duplicate of #41 so I will close this in favour of that.

**Closed as completed by jameshalsall** 2021-02-05 10:42 UTC
