### ISSUE TITLE
Service commands provide no feedback if command not found

### ISSUE THREAD

**Issue by dantleech** [my127/workspace#62] opened 2020-09-18 06:47 UTC
```
ws global service proxy starasd
ws global service proxy foobar
```

both result in ... nothing and exit code 0

Ideally the following would be good:

```
$ ws global service proxy foobar
Command "foobar" is not available on service "proxy", available commands "start", "stop", "restart"
```

and the exit code should be > 0

**Comment by jameshalsall** [comment] 2021-02-05 10:43
This is a duplicate of #36. I will migrate over your suggested DX to that issue.

**Closed as completed by jameshalsall** 2021-02-05 10:43 UTC
